RegisterNetEvent('esx_druglab:policeAlert')
AddEventHandler('esx_druglab:policeAlert', function(coords)
    local blip = AddBlipForCoord(coords.x, coords.y, coords.z)
    SetBlipSprite(blip, 161)
    SetBlipScale(blip, 1.5)
    SetBlipColour(blip, 1)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString('Verdächtige Aktivität')
    EndTextCommandSetBlipName(blip)
    Citizen.Wait(60000)
    RemoveBlip(blip)
end)
